---
- hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Startup Docker test containers
      docker_container:
        name: "{{ item }}"
        state: started
        image: "{{ image_tag }}"
      with_items:
        - docker-test-openjdk
        - docker-test-oraclejdk

- hosts: all
  user: root
  pre_tasks:
    - name: PRE_TASKS | Java | Gather OpenJDK Java version variables
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
      when: "'openjdk' in group_names"
  roles:
    - {name: java, role: . }
